name: Publish Pipeline

on:
  push:
    branches: ["main", "develop"]

jobs:
  build-jar:
    uses: firefly-oss/cicd/.github/workflows/build-maven.yaml@main
    with:
      java-version: "21"
      skip-tests: false
      jar-path: "core-lending-renting-web/target/core-lending-renting.jar"
    secrets:
      PAT_GITHUB_PACKAGE: ${{ secrets.PAT_GITHUB_PACKAGE }}
  docker-publish:
    needs: [ build-jar ]
    uses: firefly-oss/cicd/.github/workflows/docker-publish.yaml@main
    with:
      dockerfile-path: "./Dockerfile"
      image-name: "k8-infra-dev-repo"
      docker-image-tag: "core-lending-renting-1.0.0-SNAPSHOT"
    secrets:
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}